server:
  port: 8502
spring:
  application:
    name: springcloud-02
  cloud:
    consul:
      #consul的注册地址
      host: 127.0.0.1
      ##consul端口号
      port: 8500
      discovery:
        service-name: springcloud-02
        prefer-ip-address: true
        ip-address: 192.168.124.20
management:
  health:
    consul:
      enabled: false
        
